channels:
    - Muon2FJ
   # - Ele2FJ
  #  - Muon2J1FJ
  #  - Ele2J1FJ
  #  - Ele4J
 #   - Muon4J
    
run-mode: Local

skim-dir: Skim/Channels/{C}/{E}

dir: Baseline/{D}/{C}/{E}/{MHC}

processes:
    - WJ
    - DYJ
    - TT1L
    - TT2L
    - TTV
    - VV 
    - T
    - QCD

charged-masses:
    - 200
    - 300
    - 400 
    - 500
    - 600
    
data:
    Ele4J: 
        - SingleE

    Ele2J1FJ: 
        - SingleE

    Ele2FJ: 
        - SingleE

    Muon4J: 
        - SingleMu

    Muon2J1FJ: 
        - SingleMu

    Muon2FJ: 
        - SingleMu
    
parameter: EventCount
    
parameters:
    all: []
    
estimate-process:
    TT1L:
        all:
            - f:n=dnnc,v={MHC}/c:n=equal,v=2
            - f:n=dnn,v=TT1L,v={MHC}/c:n=bigger,v=0.6

        Ele4J:
            - f:n=N/p:n=e,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=0
            - f:n=N/p:n=j/c:n=bigger,v=4
            - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=2

        Muon4J:
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=e,wp=loose/c:n=equal,v=0
            - f:n=N/p:n=j/c:n=bigger,v=4
            - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=2

        Muon2FJ:
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=e,wp=loose/c:n=equal,v=0

        Ele2FJ:
            - f:n=N/p:n=e,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=0

        Ele2J1FJ:
            - f:n=N/p:n=e,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=0
            - f:n=N/p:n=j/c:n=bigger,v=2
            - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=1

        Muon2J1FJ:
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=e,wp=loose/c:n=equal,v=0
            - f:n=N/p:n=j/c:n=bigger,v=2
            - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=1
            
    TT2L:
        all:
            - f:n=dnnc,v={MHC}/c:n=equal,v=1
            - f:n=dnn,v=TT2L,v={MHC}/c:n=bigger,v=0.8

        Ele4J:
            - f:n=N/p:n=e,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=0
            - f:n=N/p:n=j/c:n=bigger,v=4
            - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=2

        Muon4J:
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=e,wp=loose/c:n=equal,v=0
            - f:n=N/p:n=j/c:n=bigger,v=4
            - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=2

        Muon2FJ:
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=e,wp=loose/c:n=equal,v=0

        Ele2FJ:
            - f:n=N/p:n=e,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=0

        Ele2J1FJ:
            - f:n=N/p:n=e,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=0
            - f:n=N/p:n=j/c:n=bigger,v=2
            - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=1

        Muon2J1FJ:
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=e,wp=loose/c:n=equal,v=0
            - f:n=N/p:n=j/c:n=bigger,v=2
            - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=1
   
    Misc:
        all:
            - f:n=dnnc,v={MHC}/c:n=equal,v=0
            - f:n=dnn,v=Misc,v={MHC}/c:n=bigger,v=0.8

        Ele4J:
            - f:n=N/p:n=e,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=0
            - f:n=N/p:n=j/c:n=bigger,v=4
            - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=2

        Muon4J:
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=e,wp=loose/c:n=equal,v=0
            - f:n=N/p:n=j/c:n=bigger,v=4
            - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=2

        Muon2FJ:
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=e,wp=loose/c:n=equal,v=0

        Ele2FJ:
            - f:n=N/p:n=e,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=0

        Ele2J1FJ:
            - f:n=N/p:n=e,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=0
            - f:n=N/p:n=j/c:n=bigger,v=2
            - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=1

        Muon2J1FJ:
            - f:n=N/p:n=mu,wp=medium/c:n=equal,v=1
            - f:n=N/p:n=e,wp=loose/c:n=equal,v=0
            - f:n=N/p:n=j/c:n=bigger,v=2
            - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=1
