shape-systs:
    all:
        - ""
        - JECTotal
        - JER
        - energyScale
        - energySigma

channels:
    - Inclusive

dir: Skim/{C}/{E}
skim-dir: Skim/{C}/{E}
dCache: Skim/{C}/{E}

run-mode: Condor


