shape-systs:
    all:
        - ""
        - JECTotal
        - JER
        - energyScale
        - energySigma

channels:
    - Inclusive

dir: Skim/27_05_21/{C}/{E}
skim-dir: Skim/27_05_21/{C}/{E}
dCache: Skim/27_05_21/{C}/{E}

run-mode: Condor
