mu4j:
    cuts: ["N_mu_0_==_1", "N_j_>=_4"]
    dir: Inclusive
    processes: 
        - "W+j"
        - "QCD"
        - "DY+j"
        - "TT+j-1L"
        - "TT+j-2L" 
        - "TT+V"
        - "VV+VVV" 
        - "T"
        - "SingleMu"
    x-parameter: 
        - pt_mu1
        - phi_mu1
        - eta_mu1
        - pt_j1
        - phi_j1
        - eta_j1
        - pt_j2
        - phi_j2
        - eta_j2
        - pt_met
        - phi_met
        - N_j 

mu2j1f:
    cuts: ["N_mu_0_==_1", "N_j_>=_2"]
    dir: Inclusive
    processes: 
        - "W+j"
        - "QCD"
        - "DY+j"
        - "TT+j-1L"
        - "TT+j-2L" 
        - "TT+V"
        - "VV+VVV" 
        - "T"
        - "SingleMu"
    x-parameter: 
        - pt_mu1
        - phi_mu1
        - eta_mu1
        - pt_j1
        - phi_j1
        - eta_j1
        - pt_fj1
        - phi_fj1
        - eta_fj1
        - pt_met
        - phi_met
        - N_j 

mu2f:
    cuts: ["N_mu_0_==_1"]
    dir: Inclusive
    processes: 
        - "W+j"
        - "QCD"
        - "DY+j"
        - "TT+j-1L"
        - "TT+j-2L" 
        - "TT+V"
        - "VV+VVV" 
        - "T"
        - "SingleMu"
    x-parameter: 
        - pt_mu1
        - phi_mu1
        - eta_mu1
        - pt_fj1
        - phi_fj1
        - eta_fj1
        - pt_fj2
        - phi_fj2
        - eta_fj2
        - pt_met
        - phi_met
        - N_j 

e4j:
    cuts: ["N_e_1_==_1", "N_j_>=_4"]
    dir: Inclusive
    processes: 
        - "W+j"
        - "QCD"
        - "DY+j"
        - "TT+j-1L"
        - "TT+j-2L" 
        - "TT+V"
        - "VV+VVV" 
        - "T"
        - "SingleE"
    x-parameter: 
        - pt_e1
        - phi_e1
        - eta_e1
        - pt_j1
        - phi_j1
        - eta_j1
        - pt_j2
        - phi_j2
        - eta_j2
        - pt_met
        - phi_met
        - N_j 

e2j1f:
    cuts: ["N_e_1_==_1", "N_j_>=_2"]
    dir: Inclusive
    processes: 
        - "W+j"
        - "QCD"
        - "DY+j"
        - "TT+j-1L"
        - "TT+j-2L" 
        - "TT+V"
        - "VV+VVV" 
        - "T"
        - "SingleE"
    x-parameter: 
        - pt_e1
        - phi_e1
        - eta_e1
        - pt_j1
        - phi_j1
        - eta_j1
        - pt_fj1
        - phi_fj1
        - eta_fj1
        - pt_met
        - phi_met
        - N_j 

e2f:
    cuts: ["N_e_1_==_1"]
    dir: Inclusive
    processes: 
        - "W+j"
        - "QCD"
        - "DY+j"
        - "TT+j-1L"
        - "TT+j-2L" 
        - "TT+V"
        - "VV+VVV" 
        - "T"
        - "SingleE"
    x-parameter: 
        - pt_e1
        - phi_e1
        - eta_e1
        - pt_fj1
        - phi_fj1
        - eta_fj1
        - pt_fj2
        - phi_fj2
        - eta_fj2
        - pt_met
        - phi_met
        - N_j 
