channels:
    - mu4j
    - e4j

dir: Inclusive

run-mode: Local

number-events: 300000

processes:
    - W+j
    - QCD
    - DY+j
    - TT+j-1L
    - TT+j-2L 
    - TT+j-H
    - TT+V
    - VV+VVV 
    - T

data:
    mu4j: 
        - SingleMu
    e4j: 
        - SingleE

x-parameters:
    all:
        - pt_met
        - phi_met
        - N_j
        - pt_j1
        - phi_j1
        - eta_j1
        - pt_j2
        - phi_j2
        - eta_j2

    mu4j:
        - pt_mu1
        - phi_mu1
        - eta_mu1

    e4j:
        - pt_e1
        - phi_e1
        - eta_e1
    
cuts:
    mu4j:
        - N_0_mu_==_1
        - N_1_e_==_0
        - N_j_\>=_4

    e4j:
        - N_1_e_==_1
        - N_0_mu_==_0
        - N_j_\>=_4
