dir: Inclusive/[C]/[E]

run-mode: Local

skim-dir: Skim/Inclusive/[E]

channels:
    - MuonIncl
    - EleIncl

processes:
    - WJ
    - DYJ
    - TT1L
    - TT2L
    - TTV
    - VV
    - ST
    - HPlus200_h100_4B
    - QCD

data:
    EleIncl: 
        - SingleE

    MuonIncl:
        - SingleMu

clean-jet:
    EleIncl: e/m
    MuonIncl: mu/m

parameters:
    all:
        - f:n=N/p:n=j/h:nxb=10,xl=0,xh=10
        - f:n=N/p:n=fj/h:nxb=4,xl=0,xh=4
        - f:n=N/p:n=bj,wp=l/h:nxb=6,xl=0,xh=6
        - f:n=N/p:n=bj,wp=m/h:nxb=6,xl=0,xh=6
        - f:n=N/p:n=bj,wp=t/h:nxb=6,xl=0,xh=6
        - f:n=N/p:n=bsj,wp=l/h:nxb=6,xl=0,xh=6
        - f:n=N/p:n=bsj,wp=m/h:nxb=6,xl=0,xh=6
        - f:n=N/p:n=bsj,wp=t/h:nxb=6,xl=0,xh=6
        - f:n=Pt/p:n=j,i=1/h:nxb=20,xl=30,xh=300
        - f:n=Pt/p:n=j,i=2/h:nxb=20,xl=30,xh=300
        - f:n=Pt/p:n=met/h:nxb=20,xl=0,xh=200
        - f:n=HT/h:nxb=20,xl=30,xh=700

    EleIncl:
        - f:n=Pt/p:n=e,i=1,wp=m/h:nxb=20,xl=20,xh=200

    MuonIncl:
        - f:n=Pt/p:n=mu,i=1,wp=m/h:nxb=20,xl=20,xh=200

cuts:
    EleIncl:
       # - f:n=N/p:n=mu,wp=m/c:n=equal,v=0
       # - f:n=Pt/p:n=e,wp=m,i=1/c:n=bigger,v=30
        - f:n=N/p:n=e,wp=m/c:n=equal,v=1

    MuonIncl:
        - f:n=N/p:n=mu,wp=m/c:n=equal,v=1
       # - f:n=Pt/p:n=mu,wp=m,i=1/c:n=bigger,v=25
       # - f:n=N/p:n=e,wp=m/c:n=equal,v=0
