dir: Preselection/{D}/{C}/{E}/{R}/{P}/{S}

n-events: 400000

run-mode: Condor

channels:
    - Muon2FJ
    - Muon2J1FJ
    - Muon4J
    - Ele2FJ
    - Ele2J1FJ
    - Ele4J

processes:
    - WJ
    - DYJ
    - TT1L
    - TT2L
    - TTV
    - VV
    - ST
    - MisIDJ
    - HPlus200_h90_4B
  #  - HPlus600_h90_4B

cuts:
    all:
        - f:n=N/p:n=trk,wp=lep/c:n=equal,v=0

    Ele2FJ:
        - f:n=N/p:n=e,wp=tight/c:n=equal,v=1/replaceForFR/getSF
        - f:n=N/p:n=e,wp=loose/c:n=equal,v=1/replaceForFR
        - f:n=gID/p:n=e,wp=loose,i=1/c:n=bigger,v=-20
        - f:n=N/p:n=mu,wp=loose/c:n=equal,v=0

    Ele2J1FJ:
        - f:n=N/p:n=e,wp=tight/c:n=equal,v=1/replaceForFR/getSF
        - f:n=N/p:n=e,wp=loose/c:n=equal,v=1/replaceForFR
        - f:n=gID/p:n=e,wp=loose,i=1/c:n=bigger,v=-20
        - f:n=N/p:n=j/c:n=bigger,v=2
        - f:n=N/p:n=mu,wp=loose/c:n=equal,v=0

    Ele4J:
        - f:n=N/p:n=e,wp=tight/c:n=equal,v=1/replaceForFR/getSF
        - f:n=N/p:n=e,wp=loose/c:n=equal,v=1/replaceForFR
        - f:n=gID/p:n=e,wp=loose,i=1/c:n=bigger,v=-20
        - f:n=N/p:n=j/c:n=bigger,v=4

    Muon2FJ:
        - f:n=N/p:n=mu,wp=tight/c:n=equal,v=1/replaceForFR/getSF
        - f:n=N/p:n=mu,wp=loose/c:n=equal,v=1/replaceForFR
        - f:n=gID/p:n=mu,wp=loose,i=1/c:n=bigger,v=-20
        - f:n=N/p:n=e,wp=loose/c:n=equal,v=0

    Muon2J1FJ:
        - f:n=N/p:n=mu,wp=tight/c:n=equal,v=1/replaceForFR/getSF
        - f:n=N/p:n=mu,wp=loose/c:n=equal,v=1/replaceForFR
        - f:n=gID/p:n=e,wp=loose,i=1/c:n=bigger,v=-20
        - f:n=N/p:n=j/c:n=bigger,v=2
        - f:n=N/p:n=e,wp=loose/c:n=equal,v=0

    Muon4J:
        - f:n=N/p:n=mu,wp=tight/c:n=equal,v=1/replaceForFR/getSF
        - f:n=N/p:n=mu,wp=loose/c:n=equal,v=1/replaceForFR
        - f:n=gID/p:n=mu,wp=loose,i=1/c:n=bigger,v=-20
        - f:n=N/p:n=e,wp=loose/c:n=equal,v=0
        - f:n=N/p:n=j/c:n=bigger,v=4

parameters:
    all:
        - f:n=dAK8C/p:n=fj,i=1/h:nxb=5,xl=0,xh=5
        - f:n=dAK8C/p:n=fj,i=2/h:nxb=5,xl=0,xh=5
        - f:n=N/p:n=bj,wp=loose/h:nxb=6,xl=0,xh=6/getSF
        - f:n=N/p:n=bj,wp=medium/h:nxb=6,xl=0,xh=6/getSF
        - f:n=N/p:n=bj,wp=tight/h:nxb=6,xl=0,xh=6/getSF
        - f:n=N/p:n=j/h:nxb=10,xl=0,xh=10
