skim-dir: Skim/27_05_21//Inclusive/{E}
out-dir: Skim/27_05_21//Channels/{C}/{E}
dir: 27_05_21//Channels/{C}/{E}

run-mode: Local

n-events: 300000

channels:
 #   Ele4J: EleIncl
 #   Ele2J1FJ: EleIncl
 #   Ele2FJ: EleIncl
 #   Muon4J: MuonIncl
  #  Muon2J1FJ: MuonIncl
    Muon2FJ: MuonIncl

shape-systs:
    all:
        - ""
        - JECTotal
        - JER

    EleIncl:
        - energyScale
        - energySigma

cuts:
    Ele4J:
        - f:n=N/p:n=fj/c:n=equal,v=0
        - f:n=N/p:n=j/c:n=bigger,v=3

    Ele2J1FJ:
        - f:n=N/p:n=fj/c:n=equal,v=1
        - f:n=N/p:n=j/c:n=bigger,v=1

    Ele2FJ:
        - f:n=N/p:n=fj/c:n=equal,v=2

    Muon4J:
        - f:n=N/p:n=fj/c:n=equal,v=0
        - f:n=N/p:n=j/c:n=bigger,v=3

    Muon2J1FJ:
        - f:n=N/p:n=fj/c:n=equal,v=1
        - f:n=N/p:n=j/c:n=bigger,v=1

    Muon2FJ:
        - f:n=N/p:n=fj/c:n=equal,v=2

dCache: Skim/Channels/{C}/{E}

exclude-merging:
    - nGen
    - nGenWeighted
    - puMC
    - nLooseBDeepbTag
    - nMediumBDeepbTag
    - nTightBDeepbTag
    - nLooseCDeepbTag
    - nMediumCDeepbTag
    - nTightCDeepbTag
    - nLooseLightDeepbTag
    - nMediumLightDeepbTag
    - nTightLightDeepbTag
    - nLooseBCSVbTag
    - nMediumBCSVbTag
    - nTightBCSVbTag
    - nLooseCCSVbTag
    - nMediumCCSVbTag
    - nTightCCSVbTag
    - nLooseLightCSVbTag
    - nMediumLightCSVbTag
    - nTightLightCSVbTag
    - nTrueB
    - nTrueC
    - nTrueLight
    - Lumi
    - xSec
    - pileUp
    - pileUpUp
    - pileUpDown
