channels:
    - mu2j1fj
    - e2j1fj
    - e2fj
    - mu2fj

processes:
    - W+j
    - QCD
    - DY+j
    - TT+j-1L
    - TT+j-2L
    - TT+j-H
    - TT+V
    - VV+VVV 
    - T
    - HPlus200_h100_4B
    - HPlus300_h100_4B
    - HPlus400_h100_4B
    - HPlus500_h100_4B
    - HPlus600_h100_4B

branch-names:
    mu2j1fj:
        - ML_HTagFJ1

    e2j1fj:
        - ML_HTagFJ1

    e2fj:
        - ML_HTagFJ1
        - ML_HTagFJ2

    mu2fj:
        - ML_HTagFJ1
        - ML_HTagFJ2

number-events: 50000
run-mode: Condor
