run-mode: Local

skim-dir: Skim/Inclusive

shape-systs:
    all:
        - ""

    #- ""
    #- energyScale
    #- energySigma
    #- JECTotal
    #- JER

scale-systs:
    all:
        - ""
       # - "BTag"
       # - "MuonIso"
       # - "MuonID"  
       # - "MuonTrigger",
       # - "EleID",  
       # - "EleReco"
       # - "PileUp"

cuts:
    all: []

data: {}

y-parameters:
    all: []
