number-events: 2500000000

run-mode: Local

skim-dir: Skim/Inclusive

shape-systs:
    - energyScale
    - energySigma
    - JECTotal
    - JER

cuts:
    all: []

data: {}

y-parameters:
    all: []
