run-mode: Local

skim-base-dir: Skim/10_10_2021/{C}/{E}

skim-dir: Skim/10_10_2021/{C}/{E}/{P}/{S}

n-events: 100000

web-dir: WebPlotting/Plots

shape-systs:
    all:
        - Nominal

scale-systs:
    all: []

cuts:
    all: []

y-parameters:
    all: []

fake-estimate:
    rates: Results/Fakerate/WithOneLepton/Rates/{C}/2018/{R}/{R}rate.root

    cuts:
        Ele2FJ:
            - f:n=N/p:n=e,wp=loose/c:n=equal,v=1
            - f:n=N/p:n=e,wp=tight/c:n=equal,v=0

        Ele2J1FJ:
            - f:n=N/p:n=e,wp=loose/c:n=equal,v=1
            - f:n=N/p:n=e,wp=tight/c:n=equal,v=0

        Ele4J:
            - f:n=N/p:n=e,wp=loose/c:n=equal,v=1
            - f:n=N/p:n=e,wp=tight/c:n=equal,v=0

        EleIncl:
            - f:n=N/p:n=e,wp=loose/c:n=equal,v=1
            - f:n=N/p:n=e,wp=tight/c:n=equal,v=0

        Muon2FJ:
            - f:n=N/p:n=mu,wp=loose/c:n=equal,v=1
            - f:n=N/p:n=mu,wp=tight/c:n=equal,v=0

        Muon2J1FJ:
            - f:n=N/p:n=mu,wp=loose/c:n=equal,v=1
            - f:n=N/p:n=mu,wp=tight/c:n=equal,v=0

        Muon4J:
            - f:n=N/p:n=mu,wp=loose/c:n=equal,v=1
            - f:n=N/p:n=mu,wp=tight/c:n=equal,v=0

        MuonIncl:
            - f:n=N/p:n=mu,wp=loose/c:n=equal,v=1
            - f:n=N/p:n=mu,wp=tight/c:n=equal,v=0

data:
    EleIncl: 
        - SingleE

    Ele4J: 
        - SingleE

    Ele2J1FJ: 
        - SingleE

    Ele2FJ: 
        - SingleE

    MuonIncl: 
        - SingleMu

    Muon4J: 
        - SingleMu

    Muon2J1FJ: 
        - SingleMu

    Muon2FJ: 
        - SingleMu
