chan-dir:
    mu4j: Muon4J
    e4j: Ele4J
    mu2j1fj: Muon2J1FJ
    e2j1fj: Ele2J1FJ
    mu2fj: Muon2FJ
    e2fj: Ele2FJ

number-events: 300000

run-mode: Local

cuts:
    all: []

data: {}

y-parameters:
    all: []
