run-mode: Local

skim-base-dir: Skim/26_8_2021/{C}/{E}

skim-dir: Skim/26_8_2021/{C}/{E}/{P}/{S}

n-events: 100000

web-dir: WebPlotting/Plots

shape-systs:
    all:
        - Nominal

scale-systs:
    all: []

cuts:
    all: []

y-parameters:
    all: []

data:
    EleIncl: 
        - SingleE

    Ele4J: 
        - SingleE

    Ele2J1FJ: 
        - SingleE

    Ele2FJ: 
        - SingleE

    MuonIncl: 
        - SingleMu

    Muon4J: 
        - SingleMu

    Muon2J1FJ: 
        - SingleMu

    Muon2FJ: 
        - SingleMu
