channels:
    - Muon2FJ
    - Ele2FJ
    - Muon2J1FJ
    - Ele2J1FJ
    - Muon4J
    - Ele4J

run-mode: Condor

hyper-opt: $CHDIR/Results/DNN/HyperOpt/{C}/{E}/hyperparameter.csv

skim-dir: Skim/Channels/{C}/{E}

masses:
    - 200
    - 300
    - 400
    - 500
    - 600

classes:
    - TT1L

Misc:
    - TT2L
    - DYJ
    - WJ
    - VV
    - T 
    - TTV

signal: HPlus{MHC}_h100_4B

dir: Test/{C}/{E}/{T}

cuts:  
    Ele4J:
        - f:n=N/p:n=e,wp=medium/c:n=equal,v=1
        - f:n=N/p:n=mu,wp=medium/c:n=equal,v=0
        - f:n=N/p:n=j/c:n=bigger,v=4
        - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=2

    Ele2J1FJ:
        - f:n=N/p:n=e,wp=medium/c:n=equal,v=1
        - f:n=N/p:n=mu,wp=medium/c:n=equal,v=0
        - f:n=N/p:n=j/c:n=bigger,v=2
        - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=1

    Ele2FJ:
        - f:n=N/p:n=e,wp=medium/c:n=equal,v=1
        - f:n=N/p:n=mu,wp=medium/c:n=equal,v=0

    Muon4J:
        - f:n=N/p:n=mu,wp=medium/c:n=equal,v=1
        - f:n=N/p:n=e,wp=loose/c:n=equal,v=0
        - f:n=N/p:n=j/c:n=bigger,v=4
        - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=2

    Muon2J1FJ:
        - f:n=N/p:n=mu,wp=medium/c:n=equal,v=1
        - f:n=N/p:n=e,wp=loose/c:n=equal,v=0
        - f:n=N/p:n=j/c:n=bigger,v=2
        - f:n=N/p:n=bj,wp=medium/c:n=bigger,v=1

    Muon2FJ:
        - f:n=N/p:n=mu,wp=medium/c:n=equal,v=1
        - f:n=N/p:n=e,wp=loose/c:n=equal,v=0

parameters:
    all:
        - f:n=HT/p:n=j
        - f:n=N/p:n=j
        - f:n=pt/p:n=met
        - f:n=phi/p:n=met

    Muon4J:
        - f:n=pt/p:n=mu,i=1
        - f:n=phi/p:n=mu,i=1
        - f:n=eta/p:n=mu,i=1
        - f:n=m/p:n=j,i=1
        - f:n=pt/p:n=j,i=1
        - f:n=phi/p:n=j,i=1
        - f:n=eta/p:n=j,i=1
        - f:n=m/p:n=j,i=2
        - f:n=pt/p:n=j,i=2
        - f:n=phi/p:n=j,i=2
        - f:n=eta/p:n=j,i=2
        - f:n=m/p:n=j,i=3
        - f:n=pt/p:n=j,i=3
        - f:n=phi/p:n=j,i=3
        - f:n=eta/p:n=j,i=3
        - f:n=m/p:n=j,i=4
        - f:n=pt/p:n=j,i=4
        - f:n=phi/p:n=j,i=4
        - f:n=eta/p:n=j,i=4

    Ele4J:
        - f:n=pt/p:n=e,i=1
        - f:n=phi/p:n=e,i=1
        - f:n=eta/p:n=e,i=1
        - f:n=m/p:n=j,i=1
        - f:n=pt/p:n=j,i=1
        - f:n=phi/p:n=j,i=1
        - f:n=eta/p:n=j,i=1
        - f:n=m/p:n=j,i=2
        - f:n=pt/p:n=j,i=2
        - f:n=phi/p:n=j,i=2
        - f:n=eta/p:n=j,i=2
        - f:n=m/p:n=j,i=3
        - f:n=pt/p:n=j,i=3
        - f:n=phi/p:n=j,i=3
        - f:n=eta/p:n=j,i=3
        - f:n=m/p:n=j,i=4
        - f:n=pt/p:n=j,i=4
        - f:n=phi/p:n=j,i=4
        - f:n=eta/p:n=j,i=4

    Muon2J1FJ:
        - f:n=pt/p:n=mu,i=1
        - f:n=phi/p:n=mu,i=1
        - f:n=eta/p:n=mu,i=1
        - f:n=m/p:n=j,i=1
        - f:n=pt/p:n=j,i=1
        - f:n=phi/p:n=j,i=1
        - f:n=eta/p:n=j,i=1
        - f:n=m/p:n=j,i=2
        - f:n=pt/p:n=j,i=2
        - f:n=phi/p:n=j,i=2
        - f:n=eta/p:n=j,i=2
        - f:n=m/p:n=fj,i=1
        - f:n=pt/p:n=fj,i=1
        - f:n=phi/p:n=fj,i=1
        - f:n=eta/p:n=fj,i=1
        - f:n=tau,v=1/p:n=fj,i=1
        - f:n=tau,v=2/p:n=fj,i=1
        - f:n=tau,v=3/p:n=fj,i=1
        - f:n=N/p:n=sj

    Ele2J1FJ:
        - f:n=pt/p:n=e,i=1
        - f:n=phi/p:n=e,i=1
        - f:n=eta/p:n=e,i=1
        - f:n=m/p:n=j,i=1
        - f:n=pt/p:n=j,i=1
        - f:n=phi/p:n=j,i=1
        - f:n=eta/p:n=j,i=1
        - f:n=m/p:n=j,i=2
        - f:n=pt/p:n=j,i=2
        - f:n=phi/p:n=j,i=2
        - f:n=eta/p:n=j,i=2
        - f:n=m/p:n=fj,i=1
        - f:n=pt/p:n=fj,i=1
        - f:n=phi/p:n=fj,i=1
        - f:n=eta/p:n=fj,i=1
        - f:n=tau,v=1/p:n=fj,i=1
        - f:n=tau,v=2/p:n=fj,i=1
        - f:n=tau,v=3/p:n=fj,i=1
        - f:n=N/p:n=sj
        
    Muon2FJ:
        - f:n=pt/p:n=mu,i=1
        - f:n=phi/p:n=mu,i=1
        - f:n=eta/p:n=mu,i=1
        - f:n=m/p:n=fj,i=1
        - f:n=pt/p:n=fj,i=1
        - f:n=phi/p:n=fj,i=1
        - f:n=eta/p:n=fj,i=1
        - f:n=m/p:n=fj,i=2
        - f:n=pt/p:n=fj,i=2
        - f:n=phi/p:n=fj,i=2
        - f:n=eta/p:n=fj,i=2
        - f:n=tau,v=1/p:n=fj,i=1
        - f:n=tau,v=2/p:n=fj,i=1
        - f:n=tau,v=3/p:n=fj,i=1
        - f:n=tau,v=1/p:n=fj,i=2
        - f:n=tau,v=2/p:n=fj,i=2
        - f:n=tau,v=3/p:n=fj,i=2
        - f:n=N/p:n=sj

    Ele2FJ:
        - f:n=pt/p:n=e,i=1
        - f:n=phi/p:n=e,i=1
        - f:n=eta/p:n=e,i=1
        - f:n=m/p:n=fj,i=1
        - f:n=pt/p:n=fj,i=1
        - f:n=phi/p:n=fj,i=1
        - f:n=eta/p:n=fj,i=1
        - f:n=m/p:n=fj,i=2
        - f:n=pt/p:n=fj,i=2
        - f:n=phi/p:n=fj,i=2
        - f:n=eta/p:n=fj,i=2
        - f:n=tau,v=1/p:n=fj,i=1
        - f:n=tau,v=2/p:n=fj,i=1
        - f:n=tau,v=3/p:n=fj,i=1
        - f:n=tau,v=1/p:n=fj,i=2
        - f:n=tau,v=2/p:n=fj,i=2
        - f:n=tau,v=3/p:n=fj,i=2
        - f:n=N/p:n=sj
