channels:
    - Muon2FJ
    - Ele2FJ
    - Muon2J1FJ
    - Ele2J1FJ
    - Muon4J
    - Ele4J

run-mode: Condor

optimize: true

n-tries: 200

index-path: Results/Index/DNNSelection/{C}/{E}/{R}/{P}/{S}

classes:
    - TT1L
    - TT2L
    - ST

signal: 
    - HPlus200_h70_4B
    - HPlus200_h80_4B
    - HPlus200_h90_4B
    - HPlus300_h100_4B
    - HPlus300_h110_4B
    - HPlus400_h100_4B
    - HPlus400_h70_4B
    - HPlus400_h80_4B
    - HPlus400_h90_4B
    - HPlus500_h100_4B
    - HPlus500_h110_4B
    - HPlus500_h70_4B
    - HPlus500_h80_4B
    - HPlus600_h100_4B
    - HPlus600_h80_4B
    - HPlus600_h90_4B

dir: HyperOpt/{D}/{C}/{E}/{R}

parameters:
    all:
        - f:n=HT/p:n=j
        - f:n=N/p:n=j
        - f:n=N/p:n=bj
        - f:n=pt/p:n=met
        - f:n=phi/p:n=met

    Muon4J:
        - f:n=diMT/p:n=mu,i=1/p:n=met
        - f:n=dphi/p:n=mu,i=1/p:n=met
        - f:n=dR/p:n=mu,i=1/p:n=j,i=1
        - f:n=dR/p:n=mu,i=1/p:n=j,i=2
        - f:n=dR/p:n=mu,i=1/p:n=j,i=3
        - f:n=dR/p:n=mu,i=1/p:n=j,i=4
        - f:n=dphi/p:n=mu,i=1/p:n=j,i=1
        - f:n=dphi/p:n=mu,i=1/p:n=j,i=2
        - f:n=dphi/p:n=mu,i=1/p:n=j,i=3
        - f:n=dphi/p:n=mu,i=1/p:n=j,i=4
        - f:n=dR/p:n=j,i=1/p:n=j,i=2
        - f:n=dR/p:n=j,i=1/p:n=j,i=3
        - f:n=dR/p:n=j,i=1/p:n=j,i=4
        - f:n=dR/p:n=j,i=2/p:n=j,i=3
        - f:n=dR/p:n=j,i=2/p:n=j,i=4
        - f:n=dR/p:n=j,i=3/p:n=j,i=4
        - f:n=dphi/p:n=j,i=1/p:n=j,i=2
        - f:n=dphi/p:n=j,i=1/p:n=j,i=3
        - f:n=dphi/p:n=j,i=1/p:n=j,i=4
        - f:n=dphi/p:n=j,i=2/p:n=j,i=3
        - f:n=dphi/p:n=j,i=2/p:n=j,i=4
        - f:n=dphi/p:n=j,i=3/p:n=j,i=4
        - f:n=diM/p:n=j,i=1/p:n=j,i=2
        - f:n=diM/p:n=j,i=1/p:n=j,i=3
        - f:n=diM/p:n=j,i=1/p:n=j,i=4
        - f:n=diM/p:n=j,i=2/p:n=j,i=3
        - f:n=diM/p:n=j,i=2/p:n=j,i=4
        - f:n=diM/p:n=j,i=3/p:n=j,i=4
        - f:n=pt/p:n=mu,i=1
        - f:n=phi/p:n=mu,i=1
        - f:n=eta/p:n=mu,i=1
        - f:n=m/p:n=j,i=1
        - f:n=pt/p:n=j,i=1
        - f:n=phi/p:n=j,i=1
        - f:n=eta/p:n=j,i=1
        - f:n=bjID/p:n=j,i=1
        - f:n=m/p:n=j,i=2
        - f:n=pt/p:n=j,i=2
        - f:n=phi/p:n=j,i=2
        - f:n=eta/p:n=j,i=2
        - f:n=bjID/p:n=j,i=2
        - f:n=m/p:n=j,i=3
        - f:n=pt/p:n=j,i=3
        - f:n=phi/p:n=j,i=3
        - f:n=eta/p:n=j,i=3
        - f:n=bjID/p:n=j,i=3
        - f:n=m/p:n=j,i=4
        - f:n=pt/p:n=j,i=4
        - f:n=phi/p:n=j,i=4
        - f:n=eta/p:n=j,i=4
        - f:n=bjID/p:n=j,i=4

    Ele4J:
        - f:n=diMT/p:n=e,i=1/p:n=met
        - f:n=dphi/p:n=e,i=1/p:n=met
        - f:n=dR/p:n=e,i=1/p:n=j,i=1
        - f:n=dR/p:n=e,i=1/p:n=j,i=2
        - f:n=dR/p:n=e,i=1/p:n=j,i=3
        - f:n=dR/p:n=e,i=1/p:n=j,i=4
        - f:n=dphi/p:n=e,i=1/p:n=j,i=1
        - f:n=dphi/p:n=e,i=1/p:n=j,i=2
        - f:n=dphi/p:n=e,i=1/p:n=j,i=3
        - f:n=dphi/p:n=e,i=1/p:n=j,i=4
        - f:n=dR/p:n=j,i=1/p:n=j,i=2
        - f:n=dR/p:n=j,i=1/p:n=j,i=3
        - f:n=dR/p:n=j,i=1/p:n=j,i=4
        - f:n=dR/p:n=j,i=2/p:n=j,i=3
        - f:n=dR/p:n=j,i=2/p:n=j,i=4
        - f:n=dR/p:n=j,i=3/p:n=j,i=4
        - f:n=dphi/p:n=j,i=1/p:n=j,i=2
        - f:n=dphi/p:n=j,i=1/p:n=j,i=3
        - f:n=dphi/p:n=j,i=1/p:n=j,i=4
        - f:n=dphi/p:n=j,i=2/p:n=j,i=3
        - f:n=dphi/p:n=j,i=2/p:n=j,i=4
        - f:n=dphi/p:n=j,i=3/p:n=j,i=4
        - f:n=diM/p:n=j,i=1/p:n=j,i=2
        - f:n=diM/p:n=j,i=1/p:n=j,i=3
        - f:n=diM/p:n=j,i=1/p:n=j,i=4
        - f:n=diM/p:n=j,i=2/p:n=j,i=3
        - f:n=diM/p:n=j,i=2/p:n=j,i=4
        - f:n=diM/p:n=j,i=3/p:n=j,i=4
        - f:n=pt/p:n=e,i=1
        - f:n=phi/p:n=e,i=1
        - f:n=eta/p:n=e,i=1
        - f:n=m/p:n=j,i=1
        - f:n=pt/p:n=j,i=1
        - f:n=phi/p:n=j,i=1
        - f:n=eta/p:n=j,i=1
        - f:n=bjID/p:n=j,i=1
        - f:n=m/p:n=j,i=2
        - f:n=pt/p:n=j,i=2
        - f:n=phi/p:n=j,i=2
        - f:n=eta/p:n=j,i=2
        - f:n=bjID/p:n=j,i=2
        - f:n=m/p:n=j,i=3
        - f:n=pt/p:n=j,i=3
        - f:n=phi/p:n=j,i=3
        - f:n=eta/p:n=j,i=3
        - f:n=bjID/p:n=j,i=3
        - f:n=m/p:n=j,i=4
        - f:n=pt/p:n=j,i=4
        - f:n=phi/p:n=j,i=4
        - f:n=eta/p:n=j,i=4
        - f:n=bjID/p:n=j,i=4

    Muon2J1FJ:
        - f:n=diMT/p:n=mu,i=1/p:n=met
        - f:n=dphi/p:n=mu,i=1/p:n=met
        - f:n=dR/p:n=mu,i=1/p:n=j,i=1
        - f:n=dR/p:n=mu,i=1/p:n=j,i=2
        - f:n=dR/p:n=mu,i=1/p:n=fj,i=1
        - f:n=dphi/p:n=mu,i=1/p:n=j,i=1
        - f:n=dphi/p:n=mu,i=1/p:n=j,i=2
        - f:n=dphi/p:n=mu,i=1/p:n=fj,i=1
        - f:n=dR/p:n=j,i=1/p:n=j,i=2
        - f:n=dR/p:n=j,i=1/p:n=fj,i=1
        - f:n=dR/p:n=j,i=2/p:n=fj,i=1
        - f:n=dphi/p:n=j,i=1/p:n=j,i=2
        - f:n=dphi/p:n=j,i=1/p:n=fj,i=1
        - f:n=dphi/p:n=j,i=2/p:n=fj,i=1
        - f:n=diM/p:n=j,i=1/p:n=j,i=2
        - f:n=pt/p:n=mu,i=1
        - f:n=phi/p:n=mu,i=1
        - f:n=eta/p:n=mu,i=1
        - f:n=m/p:n=j,i=1
        - f:n=pt/p:n=j,i=1
        - f:n=phi/p:n=j,i=1
        - f:n=eta/p:n=j,i=1
        - f:n=bjID/p:n=j,i=1
        - f:n=m/p:n=j,i=2
        - f:n=pt/p:n=j,i=2
        - f:n=phi/p:n=j,i=2
        - f:n=eta/p:n=j,i=2
        - f:n=bjID/p:n=j,i=2
        - f:n=m/p:n=fj,i=1
        - f:n=pt/p:n=fj,i=1
        - f:n=phi/p:n=fj,i=1
        - f:n=eta/p:n=fj,i=1
        - f:n=tau,v=1/p:n=fj,i=1
        - f:n=tau,v=2/p:n=fj,i=1
        - f:n=tau,v=3/p:n=fj,i=1
        - f:n=N/p:n=sj

    Ele2J1FJ:
        - f:n=diMT/p:n=e,i=1/p:n=met
        - f:n=dphi/p:n=e,i=1/p:n=met
        - f:n=dR/p:n=e,i=1/p:n=j,i=1
        - f:n=dR/p:n=e,i=1/p:n=j,i=2
        - f:n=dR/p:n=e,i=1/p:n=fj,i=1
        - f:n=dphi/p:n=e,i=1/p:n=j,i=1
        - f:n=dphi/p:n=e,i=1/p:n=j,i=2
        - f:n=dphi/p:n=e,i=1/p:n=fj,i=1
        - f:n=dR/p:n=j,i=1/p:n=j,i=2
        - f:n=dR/p:n=j,i=1/p:n=fj,i=1
        - f:n=dR/p:n=j,i=2/p:n=fj,i=1
        - f:n=dphi/p:n=j,i=1/p:n=j,i=2
        - f:n=dphi/p:n=j,i=1/p:n=fj,i=1
        - f:n=dphi/p:n=j,i=2/p:n=fj,i=1
        - f:n=diM/p:n=j,i=1/p:n=j,i=2
        - f:n=pt/p:n=e,i=1
        - f:n=phi/p:n=e,i=1
        - f:n=eta/p:n=e,i=1
        - f:n=m/p:n=j,i=1
        - f:n=pt/p:n=j,i=1
        - f:n=phi/p:n=j,i=1
        - f:n=eta/p:n=j,i=1
        - f:n=bjID/p:n=j,i=1
        - f:n=m/p:n=j,i=2
        - f:n=pt/p:n=j,i=2
        - f:n=phi/p:n=j,i=2
        - f:n=eta/p:n=j,i=2
        - f:n=bjID/p:n=j,i=2
        - f:n=m/p:n=fj,i=1
        - f:n=pt/p:n=fj,i=1
        - f:n=phi/p:n=fj,i=1
        - f:n=eta/p:n=fj,i=1
        - f:n=tau,v=1/p:n=fj,i=1
        - f:n=tau,v=2/p:n=fj,i=1
        - f:n=tau,v=3/p:n=fj,i=1
        - f:n=N/p:n=sj
        
    Muon2FJ:
        - f:n=diMT/p:n=mu,i=1/p:n=met
        - f:n=dphi/p:n=mu,i=1/p:n=met
        - f:n=dR/p:n=mu,i=1/p:n=fj,i=1
        - f:n=dR/p:n=mu,i=1/p:n=fj,i=2
        - f:n=dphi/p:n=mu,i=1/p:n=fj,i=1
        - f:n=dphi/p:n=mu,i=1/p:n=fj,i=2
        - f:n=dR/p:n=fj,i=1/p:n=fj,i=2
        - f:n=dphi/p:n=fj,i=1/p:n=fj,i=2
        - f:n=pt/p:n=mu,i=1
        - f:n=phi/p:n=mu,i=1
        - f:n=eta/p:n=mu,i=1
        - f:n=m/p:n=fj,i=1
        - f:n=pt/p:n=fj,i=1
        - f:n=phi/p:n=fj,i=1
        - f:n=eta/p:n=fj,i=1
        - f:n=m/p:n=fj,i=2
        - f:n=pt/p:n=fj,i=2
        - f:n=phi/p:n=fj,i=2
        - f:n=eta/p:n=fj,i=2
        - f:n=tau,v=1/p:n=fj,i=1
        - f:n=tau,v=2/p:n=fj,i=1
        - f:n=tau,v=3/p:n=fj,i=1
        - f:n=tau,v=1/p:n=fj,i=2
        - f:n=tau,v=2/p:n=fj,i=2
        - f:n=tau,v=3/p:n=fj,i=2
        - f:n=N/p:n=sj

    Ele2FJ:
        - f:n=diMT/p:n=e,i=1/p:n=met
        - f:n=dphi/p:n=e,i=1/p:n=met
        - f:n=dR/p:n=e,i=1/p:n=fj,i=1
        - f:n=dR/p:n=e,i=1/p:n=fj,i=2
        - f:n=dphi/p:n=e,i=1/p:n=fj,i=1
        - f:n=dphi/p:n=e,i=1/p:n=fj,i=2
        - f:n=dR/p:n=fj,i=1/p:n=fj,i=2
        - f:n=dphi/p:n=fj,i=1/p:n=fj,i=2
        - f:n=pt/p:n=e,i=1
        - f:n=phi/p:n=e,i=1
        - f:n=eta/p:n=e,i=1
        - f:n=m/p:n=fj,i=1
        - f:n=pt/p:n=fj,i=1
        - f:n=phi/p:n=fj,i=1
        - f:n=eta/p:n=fj,i=1
        - f:n=m/p:n=fj,i=2
        - f:n=pt/p:n=fj,i=2
        - f:n=phi/p:n=fj,i=2
        - f:n=eta/p:n=fj,i=2
        - f:n=tau,v=1/p:n=fj,i=1
        - f:n=tau,v=2/p:n=fj,i=1
        - f:n=tau,v=3/p:n=fj,i=1
        - f:n=tau,v=1/p:n=fj,i=2
        - f:n=tau,v=2/p:n=fj,i=2
        - f:n=tau,v=3/p:n=fj,i=2
        - f:n=N/p:n=sj
